---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Create ansible.cfg with correct roles_path
  - echo '[defaults]\nroles_path=../' > ansible.cfg

  # Basic role syntax check
  - ansible-playbook travis-tests/test.yml -i travis-tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
